import{a as B,S as E,i as M}from"./assets/vendor-NHa_OlqX.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const $="57930041-98ffbfcb0d5f6c92ccc9089fe",O="https://pixabay.com/api/",f=15;async function m(r,t){return(await B.get(O,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:f}})).data}const y=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more"),x=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const t=r.map(({webformatURL:s,largeImageURL:l,tags:e,likes:o,views:n,comments:q,downloads:P})=>`<li class="gallery-item">
  <a class="gallery-link" href="${l}">
    <img class="gallery-image" src="${s}" alt="${e}" />
  </a>
  <ul class="info">
    <li class="info-item"><b>Likes</b><span>${o}</span></li>
    <li class="info-item"><b>Views</b><span>${n}</span></li>
    <li class="info-item"><b>Comments</b><span>${q}</span></li>
    <li class="info-item"><b>Downloads</b><span>${P}</span></li>
  </ul>
</li>`).join("");y.insertAdjacentHTML("beforeend",t),x.refresh()}function A(){y.innerHTML=""}function b(){p.classList.add("is-active")}function L(){p.classList.remove("is-active")}function w(){h.classList.add("is-visible")}function u(){h.classList.remove("is-visible")}const d=document.querySelector(".form"),_=document.querySelector(".load-more");let c="",a=1,v=0;function i(r,t){M[r]({message:t,position:"topRight"})}function S(){a*f>=v?(u(),i("info","We're sorry, but you've reached the end of search results.")):w()}function D(){const r=document.querySelector(".gallery-item"),{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}d.addEventListener("submit",async r=>{r.preventDefault();const t=d.elements["search-text"].value.trim();if(!t){i("warning","Please enter a search query.");return}c=t,a=1,A(),u(),b();try{const s=await m(c,a);if(s.hits.length===0){i("error","Sorry, there are no images matching your search query. Please try again!");return}v=s.totalHits,g(s.hits),S()}catch{i("error","Something went wrong. Please try again later.")}finally{L()}});_.addEventListener("click",async()=>{a+=1,u(),b();try{const r=await m(c,a);g(r.hits),D(),S()}catch{a-=1,w(),i("error","Something went wrong. Please try again later.")}finally{L()}});
//# sourceMappingURL=index.js.map
